export const images = {
  question: ('/images/question.png'),
  dtwitter: ('/images/dtwitter.svg'),
  dinstagram: ('/images/dinstagram.svg'),
  dfacebook: ('/images/dfacebook.svg'),
  content_Provider: ('/images/content-provide.png'),

  dollaranimation: ('/images/Dollaranimation.png'),
  hearts: ('/images/hearts1.png'),
  contact: ('/images/contact.png'),
  elipse: ('/images/Ellipse.png'),
  elipseright: ('/images/Ellipserigh.png'),
  WelcomeLogo: ('/images/Illustration.svg'),
  whatimg: ('/images/what.png'),
  webhost: ('/images/webhost.svg'),
  donor: ('/images/donor.svg'),
  contentProvider: ('/images/contentprovider.svg'),
  Welcome: ('/images/welcome_to_iresonate.svg'),
  ClickTip: ('/images/clicktip_button.svg'),
  Banner: ('/images/baner.png'),
  Vector1: ('images/whatimage.png'),
  vector2: ('images/vector2.png'),
  Vector3: ('images/whoimg.png'),
  Vector4: ('images/vector4.png'),
  Dashboard: ('/images/dashboard.svg'),
  ProcessVector: ('/images/process_vector.svg'),
  slide: [
    ("/images/slidestep1.png"),
    ("/images/slidestep2.png"),
    ("/images/slidestep3.png"),
    ("/images/slidestep4.png")
  ],
  Step1: ("/images/step1.png"),
  Step2: ("/images/step2.png"),
  Step3: ("/images/step3.png"),
  Step4: ("/images/step4.png"),
  ZF: ("/images/zf.png"),
  SP: ("/images/sp.png"),
  EA: ("/images/ea.png"),
  VR: ("/images/vr.png"),
  ViharRana: ("/images/vihar_rana.png"),
  IResonate_2: ("images/iresonate_2.svg"),
  edit: ("/images/editing.png"),
  facebook: ("/images/facebook.png"),
  phone: ("/images/phone.png"),
  mail: ("/images/mail.png"),
  iResonate: ("/images/iresonate.png"),
  CEO: ("/images/CEO.png"),
  iResonatefooter: ("/images/IllustrationFoter.png"),
  stripeIcon: ("/images/stripe-icon.png"),
  success: ("/images/success.png"),
  dollarIcon: ("/images/dollar-icon.svg"),
  user: ("/images/user.png"),
  email: ("/images/email.png"),
  mobile: ("/images/mobile.png"),
  footerleft: ('/images/footerleft.png'),
  footerRight: ('/images/footerRight.png'),
  slideleft: ('/images/slideleft.png'),
  slideright: ('/images/slideright.png'),

}